# Generated by Django 4.2.17 on 2025-01-06 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(default='5', max_length=1)),
                ('kanji', models.CharField(blank=True, max_length=100, null=True)),
                ('kana', models.CharField(blank=True, max_length=100, null=True)),
                ('romaji', models.CharField(blank=True, max_length=100, null=True)),
                ('translate_ru', models.CharField(blank=True, max_length=200, null=True)),
                ('translate_en', models.CharField(blank=True, max_length=200, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['level', 'kanji', 'kana'],
            },
        ),
        migrations.CreateModel(
            name='Word_translate_variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_translate_ru', models.TextField(blank=True, null=True)),
                ('add_translate_en', models.TextField(blank=True, null=True)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fake_translate', to='blog.word')),
            ],
        ),
        migrations.CreateModel(
            name='Word_kanji_variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_kanji', models.TextField(blank=True, null=True)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fake_kanji', to='blog.word')),
            ],
        ),
        migrations.CreateModel(
            name='Word_kana_variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_kana', models.TextField(blank=True, null=True)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fake_kana', to='blog.word')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Kanji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=5)),
                ('kanji', models.CharField(max_length=100)),
                ('onyomi', models.CharField(blank=True, max_length=100, null=True)),
                ('kunyomi', models.CharField(blank=True, max_length=100, null=True)),
                ('meaning_ru', models.CharField(blank=True, max_length=200, null=True)),
                ('meaning_en', models.CharField(blank=True, max_length=200, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['level', 'kanji'],
            },
        ),
        migrations.CreateModel(
            name='Grammar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=5)),
                ('title_ru', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200)),
                ('explain_ru', models.TextField(blank=True, null=True)),
                ('explain_en', models.TextField(blank=True, null=True)),
                ('example_jp_kanji', models.TextField(blank=True, null=True)),
                ('example_jp_kana', models.TextField(blank=True, null=True)),
                ('example_ru', models.TextField(blank=True, null=True)),
                ('example_en', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['level', 'title_ru', 'title_en'],
            },
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_example_jp_kanji', models.TextField(blank=True, null=True)),
                ('add_example_jp_kana', models.TextField(blank=True, null=True)),
                ('add_example_ru', models.TextField(blank=True, null=True)),
                ('add_example_en', models.TextField(blank=True, null=True)),
                ('grammar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='blog.grammar')),
            ],
        ),
    ]
