# Generated by Django 4.2.17 on 2024-12-30 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Grammar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=5)),
                ('title_ru', models.CharField(default='Des', max_length=200)),
                ('title_en', models.CharField(default='Des', max_length=200)),
                ('explain_ru', models.TextField(blank=True, null=True)),
                ('explain_en', models.TextField(blank=True, null=True)),
                ('example_jp_kanji', models.TextField(blank=True, null=True)),
                ('example_ru_kana', models.TextField(blank=True, null=True)),
                ('example_ru', models.TextField(blank=True, null=True)),
                ('example_en', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_example_jp_kanji', models.TextField(blank=True, null=True)),
                ('add_example_ru_kana', models.TextField(blank=True, null=True)),
                ('add_example_en_ru', models.TextField(blank=True, null=True)),
                ('add_example_en_en', models.TextField(blank=True, null=True)),
                ('grammar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='blog.grammar')),
            ],
        ),
    ]
