# Generated by Django 4.2.17 on 2025-01-01 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grammar',
            name='example_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grammar',
            name='example_jp_kana',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grammar',
            name='example_jp_kanji',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grammar',
            name='example_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grammar',
            name='explain_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grammar',
            name='explain_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grammar',
            name='title_en',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='grammar',
            name='title_ru',
            field=models.CharField(max_length=200),
        ),
    ]
