# Generated by Django 4.2.17 on 2024-12-30 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grammar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('explain_ru', models.TextField()),
                ('explain_en', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('example_jp', models.TextField()),
                ('example_ru', models.TextField()),
                ('example_en', models.TextField()),
                ('grammar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='blog.grammar')),
            ],
        ),
    ]
