# Generated by Django 4.2.17 on 2025-01-02 00:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_alter_grammar_example_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=5)),
                ('kanji', models.CharField(blank=True, max_length=100, null=True)),
                ('kana', models.CharField(blank=True, max_length=100, null=True)),
                ('translate_ru', models.CharField(blank=True, max_length=200, null=True)),
                ('translate_en', models.CharField(blank=True, max_length=200, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['level', 'kanji', 'kana'],
            },
        ),
    ]
