# Generated by Django 4.2.17 on 2025-01-08 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_grammar_formula_alter_grammar_title_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grammar',
            options={'ordering': ['level', 'title']},
        ),
        migrations.RenameField(
            model_name='grammar',
            old_name='formula',
            new_name='formula_en',
        ),
        migrations.RenameField(
            model_name='grammar',
            old_name='title_en',
            new_name='formula_ru',
        ),
        migrations.RenameField(
            model_name='grammar',
            old_name='title_ru',
            new_name='title',
        ),
    ]
