# Generated by Django 4.2.17 on 2024-12-30 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_grammar_example'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grammar',
            name='level',
            field=models.IntegerField(default=5),
        ),
    ]
