# Generated by Django 4.2.17 on 2025-01-08 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_grammar_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grammar',
            options={'ordering': ['title', 'level']},
        ),
        migrations.AlterField(
            model_name='grammar',
            name='level',
            field=models.CharField(default='5', max_length=1),
        ),
    ]
