# Generated by Django 4.2.17 on 2025-01-03 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='romaji',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
