# Generated by Django 4.2.17 on 2025-01-03 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_word_romaji'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grammar',
            options={'ordering': ['level', 'title_ru', 'title_en']},
        ),
        migrations.CreateModel(
            name='Kanji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=5)),
                ('kanji', models.CharField(max_length=100)),
                ('oyomi', models.CharField(blank=True, max_length=100, null=True)),
                ('kunyomi', models.CharField(blank=True, max_length=100, null=True)),
                ('Meaning_ru', models.CharField(blank=True, max_length=200, null=True)),
                ('Meaning_en', models.CharField(blank=True, max_length=200, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['level', 'kanji'],
            },
        ),
    ]
