# Generated by Django 4.2.17 on 2025-01-03 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_grammar_options_kanji'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kanji',
            old_name='oyomi',
            new_name='onyomi',
        ),
    ]
