# Generated by Django 4.2.17 on 2025-01-26 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_word_part_of_speech'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
