# Generated by Django 4.2.17 on 2025-01-03 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_oyomi_kanji_onyomi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kanji',
            old_name='Meaning_en',
            new_name='meaning_en',
        ),
        migrations.RenameField(
            model_name='kanji',
            old_name='Meaning_ru',
            new_name='meaning_ru',
        ),
    ]
