# Generated by Django 4.2.17 on 2025-01-05 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_meaning_en_kanji_meaning_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word_translate_variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_translate_ru', models.TextField(blank=True, null=True)),
                ('add_translate_en', models.TextField(blank=True, null=True)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fake_translate', to='blog.word')),
            ],
        ),
        migrations.CreateModel(
            name='Word_kanji_variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_kanji', models.TextField(blank=True, null=True)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fake_kanji', to='blog.word')),
            ],
        ),
        migrations.CreateModel(
            name='Word_kana_variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_kana', models.TextField(blank=True, null=True)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fake_kana', to='blog.word')),
            ],
        ),
    ]
