# Generated by Django 4.2.17 on 2025-05-12 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_word_part_of_speech'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grammar',
            options={'ordering': ['level', 'title']},
        ),
    ]
