# Generated by Django 4.2.17 on 2025-05-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_grammar_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartOfSpeech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='word',
            name='part_of_speech',
        ),
        migrations.AddField(
            model_name='word',
            name='part_of_speech',
            field=models.ManyToManyField(blank=True, to='blog.partofspeech'),
        ),
    ]
