# Generated by Django 4.2.17 on 2025-07-15 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_kanji_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanji',
            name='radical',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='kanji',
            name='kanji',
            field=models.CharField(max_length=1),
        ),
    ]
