# Generated by Django 4.2.17 on 2025-07-16 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_kanji_radical_alter_kanji_kanji'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='examples',
            field=models.JSONField(blank=True, help_text='Примеры предложений (список словарей)', null=True),
        ),
    ]
