# Generated by Django 4.2.17 on 2025-07-16 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_word_examples'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='examples',
            field=models.TextField(blank=True, help_text='Примеры предложений (сохранять как JSON-строку)', null=True),
        ),
    ]
