# Generated by Django 4.2.17 on 2025-07-29 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_word_examples'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='auto_translated_ru',
            field=models.BooleanField(default=False),
        ),
    ]
