# Generated by Django 4.2.17 on 2025-08-14 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_word_auto_translated_ru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanji',
            name='level',
            field=models.CharField(db_index=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='kanji',
            name='radical',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='level',
            field=models.CharField(db_index=True, default='5', max_length=1),
        ),
    ]
