# Generated by Django 4.2.17 on 2025-08-27 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0015_alter_kanji_level_alter_kanji_radical_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KanjiSentenceQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'N1'), (2, 'N2'), (3, 'N3'), (4, 'N4'), (5, 'N5')], db_index=True)),
                ('sentence_kanji', models.TextField()),
                ('sentence_kana', models.TextField()),
                ('question_kanji', models.CharField(max_length=64)),
                ('question_kana', models.CharField(max_length=64)),
                ('translation_en', models.TextField(blank=True, default='')),
                ('translation_ru', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ksq', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KanjiSentenceFake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=64)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fakes', to='blog.kanjisentencequestion')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='kanjisentencequestion',
            index=models.Index(fields=['level'], name='blog_kanjis_level_de6cda_idx'),
        ),
        migrations.AddConstraint(
            model_name='kanjisentencequestion',
            constraint=models.UniqueConstraint(fields=('sentence_kanji', 'question_kanji'), name='uniq_sentence_question_pair'),
        ),
        migrations.AlterUniqueTogether(
            name='kanjisentencefake',
            unique_together={('question', 'text')},
        ),
    ]
